channels:
  # Define conda channels here.
  - conda-forge

dependencies:
  - python=3.9.13
  - black=22.3.0
  - pydantic=1.9.1
  - pandas==1.4.2
  - retry==0.9.2
  - pip=22.1
  - pip:
      - rpaframework==15.0.0
